package org.example.token

enum class TokenType {
    IDENTIFIER,
    KEYWORD,
    PUNCTUATOR,
    OPERATOR,
    STRINGLITERAL,
    NUMBERLITERAL,
    DECLARATOR,
    ASSIGNATION,
    PARENTHESIS,
    BOOLEAN,
    TYPE_OF_DATA,
    FUNCTION,
    CONDITIONAL,
    DATA_TYPE,
    ASSIGN,
    UNKNOWN,
    LITERAL,
}
